# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails_action_args}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ezmobius", "mattetti", "maiha", "Yehuda Katz", "Andy Delcambre", "Janne Asmala", "Collin Miller"]
  s.date = %q{2010-02-05}
  s.description = %q{Big thanks to the original authors. Let me know if I missed you. Action args rocks and you deserve the credit :)}
  s.email = %q{collintmiller@gmail.com}
  s.executables = ["autotest", "convert_to_should_syntax", "erubis", "multigem", "multiruby", "multiruby_setup", "parse_tree_abc", "parse_tree_audit", "parse_tree_deps", "parse_tree_show", "r2r_show", "rackup", "rake", "ruby_parse", "unit_diff", "zentest"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "TODO",
     "ThankYou",
     "VERSION",
     "init.rb",
     "lib/rails_action_args.rb",
     "lib/rails_action_args/abstract_controller.rb",
     "lib/rails_action_args/get_args.rb",
     "lib/rails_action_args/jruby_args.rb",
     "lib/rails_action_args/mri_args.rb",
     "lib/rails_action_args/plugin.rb",
     "lib/rails_action_args/vm_args.rb",
     "rails_action_args.gemspec",
     "test/test_rails_action_args.rb"
  ]
  s.homepage = %q{http://github.com/collin/rails_action_args}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A port of merb-action-args to rails}
  s.test_files = [
    "test/test_rails_action_args.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 3.0.pre"])
      s.add_runtime_dependency(%q<ParseTree>, [">= 3.0.4"])
      s.add_runtime_dependency(%q<ruby2ruby>, [">= 1.2.4"])
    else
      s.add_dependency(%q<actionpack>, [">= 3.0.pre"])
      s.add_dependency(%q<ParseTree>, [">= 3.0.4"])
      s.add_dependency(%q<ruby2ruby>, [">= 1.2.4"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 3.0.pre"])
    s.add_dependency(%q<ParseTree>, [">= 3.0.4"])
    s.add_dependency(%q<ruby2ruby>, [">= 1.2.4"])
  end
end

